<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="gender" nsURI="http://model.data.jena.de/main/main/gender" nsPrefix="main_gender">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation.en" value="data models referring to gender"/>
    <details key="documentation" value="Datenmodelle bezüglich Geschlecht"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="common" value="http://model.data.jena.de/main/common"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Gender" abstract="true">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation.en" value="basic class providing common attributes used by specific gender structures"/>
      <details key="documentation" value="Basisklasse mit allgemeingültigen Attributen für konkrete Geschlechterstrukturen"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenderOld" eSuperTypes="#//Gender">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation.en" value="Historical gender determination according to §§ 21 par.1 no. 3, 22 par. 3 PersStG until its version dated 18 November 2018 (male, female, unknown)"/>
      <details key="documentation" value="Historische Unterscheidung des Geschlechts i.S.d. §§ 21 Abs.1 Nr. 3 und 22 Abs. 3 PersStG bis zur Fassung vom 01.11.2018 (männlich, weiblich, unbekannt)"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GenderNew" eSuperTypes="#//Gender">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation.en" value="Contemporary gender determination according to §§ 21 par.1 no. 3, 22 par. 3, 45 b PersStG since its version dated 18 December 2018 (male, female, diverse, unknown)"/>
      <details key="documentation" value="Derzeitige Unterscheidung des Geschlechts i.S.d. §§ 21 Abs.1 Nr. 3, 22 Abs. 3 und 45 b PersStG ab der Fassung vom 18.12.2018 (männlich, weiblich, divers, unbekannt)"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
